### ISSUE TITLE
Set homepage setting to GitHub repo (Scala Steward improvement)

### ISSUE THREAD

**Issue by calvellido** [47deg/sbt-microsites#369]
As pointed in this tweet by @fthomas:

https://twitter.com/fst9000/status/1194716047376560129

We need to set the `homepage` setting to the GitHub one, so Scala Steward could fetch the GitHub repo URL, version diff, and release notes accordingly when notifying users about an update.

You can see the difference by checking this PR, current own `homepage` not being set to the one Scala Steward expects:

https://github.com/47deg/sbt-microsites/pull/345

And this one, that includes the GitHub URL as `homepage`:

https://github.com/47deg/sbt-microsites/pull/355

**Comment by fthomas** [comment]
Hmm, sbt-microsites is published on Maven Central and not in the [sbt-plugin-releases](https://dl.bintray.com/sbt/sbt-plugin-releases/) Ivy repository and the [POM](https://repo1.maven.org/maven2/com/47deg/sbt-microsites_2.12_1.0/0.9.7/sbt-microsites-0.9.7.pom) already has the `scm.url` element set, so adding `homepage` shouldn't be necessary here. I'll check why Scala Steward is not using the `scm.url` from the POM.

**Comment by calvellido** [comment]
Oh, I wasn't sure, but anyway I went on as I didn't see the info being populated on Scala Steward messages. I'll keep an eye on next Scala Steward commits to see if any additional work would be needed in our end.

Thanks a lot @fthomas!

**Comment by fthomas** [comment]
I just verified locally that Scala Steward extracts the `scm.url` from the POM. That URL wasn't used for any sbt-microsites PRs because 0.9.7 is older than the change in Scala Steward that enables it to read POMs of sbt plugins (https://github.com/fthomas/scala-steward/pull/1044). So as I already said, setting `homepage` for plugins on Maven Central isn't necessary, but it does not hurt either. :-)

**Comment by calvellido** [comment]
Ah, great then!  Thank you very much for the help @fthomas! :hugs:
